// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProjectPackageString = "00fc11fd-5709-4f80-a45e-69bb017d8742";
        public static Guid guidVSIXProjectPackage = new Guid(guidVSIXProjectPackageString);

        public const string guidVSIXProjectPackageCmdSetString = "04573336-d76c-4f4b-a66a-74ca1ff31b38";
        public static Guid guidVSIXProjectPackageCmdSet = new Guid(guidVSIXProjectPackageCmdSetString);

        public const string guidImagesString = "453c6ea9-2575-410f-b560-b42190269b4d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}